== Frequently Asked Questions

=== Selenwright in Kubernetes

We are very frequently asked whether it is possible to run Selenwright in https://kubernetes.io[Kubernetes] cluster. The answer is - **it is possible but we do not recommend doing this**:

. Selenwright can **only** work directly with https://docs.docker.com/engine/api/latest/[Docker API] and was created to be run on a workstation or a virtual machine with Docker installed.
. Kubernetes contrarily has a completely different https://kubernetes.io/docs/concepts/overview/kubernetes-api/[API] and **can be using Docker** as a container runtime backend. In some clusters https://github.com/rkt/rkt[rkt] is used instead of Docker and in that case Selenwright will not work.
. Even if Selenwright works - **all browser containers will be started on the same Kubernetes node** where it is running.
. So far as Selenwright is using Docker API directly - Kubernetes will not be aware of additional containers started by Selenwright. This is dangerous and **can potentially lead to overloaded Kubernetes nodes**.
. You can only have **one Selenwright replica maximum**. This is because Selenwright internally stores a list of running sessions in memory.

If you need Selenium in Kubernetes or https://www.openshift.com/[Openshift], we have a separate solution called https://aerokube.com/moon/[Moon].

=== Logs and Dirs

**Where are Selenwright logs?**

Selenwright outputs its logs to stdout. Selenwright launched as a binary should output logs to the screen. To see Selenwright logs launched as Docker container type:

    $ docker logs selenwright

To follow the logs add one more flag:

    $ docker logs -f selenwright

**Where are recorded videos stored?**

Default location when installed with `cm` is `~/.aqa-alex/selenwright/video` or `C:\Users\<user>\.aerokube\selenwright\video`.

=== Limits and Timeouts

**How can I limit overall browsers consumption?**

You have to use `-limit` flag to specify total number of parallel sessions. Default value is 5. See <<Resources Consumption>> section on how to determine total number of parallel sessions.

**Can I limit per-version browser consumption?**

No, this is not supported. We consider the only reasonable limitation should be the overall browsers consumption. This is important to not overload the hardware.

**How can I adjust Selenwright timeouts?**

The main timeout flag is `-timeout`, specified as `60s` or `2m` or `1h`. It means maximum amount of time between subsequent HTTP requests to Selenium API. When there are no requests during this time period - session is automatically closed. Selenwright also has more subtle timeouts like:

* `-service-startup-timeout` - container or driver process startup timeout
* `-session-attempt-timeout` - new session HTTP request timeout, applied when container or driver has started
* `-session-delete-timeout` - container or process removal timeout, applied after `driver.quit()` call

=== Resources Consumption

**How many resources browser containers consume?**

This depends on your tests. We recommend to start with 1 CPU and 1 Gb of memory per container as a rough estimate and then increase `-limit` checking that your tests work stably.

**Do VNC and non-VNC browser images memory and CPU consumption differ?**

The only difference between these images - is a running VNC server (`x11vnc`) consuming approximately 20 Megabytes of RAM in idle state which is negligible compared to browser memory consumption.

**VNC is consuming all my container CPU**

On RedHat-based distributions you should set `LimitNOFILE=1048576` for `containerd.service`

=== Features not Working

**Selenwright does not start: open config/browsers.json: no such file or directory**

This usually happens when Selenwright is started in Docker container with custom command-line arguments, e.g.:

    $ docker run <some-args> aqa-alex/selenwright:some-version -limit 10

In that case you have to specify path to configuration file explicitly (`cm` tool does this automatically):

    $ docker run <some-args> aqa-alex/selenwright:some-version -limit 10 -conf /etc/selenwright/browsers.json

**Getting error: create container: Error response from daemon: client version 1.36 is too new**

You have to run Selenwright binary \ container with `DOCKER_API_VERSION` variable specifying your Docker API version. `cm` tool does this automatically for you. To determine API version type:

    $ docker version | grep API

Then run Selenwright like the following:

    $ DOCKER_API_VERSION=1.32 ./selenwright <rest-of-args> # As a binary
    $ docker run -e DOCKER_API_VERSION=1.32 <rest-of-args> aqa-alex/selenwright:some-version # As Docker container

**Video feature not working**

When running Selenwright as Docker container video feature can be not working (because of misconfiguration). If your video files are named like `selenwright607667f7e1c7923779e35506b040300d.mp4` and you are seeing the following log message...
```
2018/03/20 21:06:37 [9] [VIDEO_ERROR] [Failed to rename /video/selenwright607667f7e1c7923779e35506b040300d.mp4 to /video/8019c4bc-9bec-4a8b-aa40-68d1db0cffd2.mp4: rename /video/selenwright607667f7e1c7923779e35506b040300d.mp4 /video/8019c4bc-9bec-4a8b-aa40-68d1db0cffd2.mp4: no such file or directory]
```
\... then check that:

. You are passing an `OVERRIDE_VIDEO_OUTPUT_DIR` environment variable pointing to a directory on the `host machine` where video files are actually stored
. When passing custom arguments to Selenwright container (such as `-limit` or `-timeout`) you also have to pass `-video-output-dir /opt/selenwright/video` and mount host machine video dir to `/opt/selenwright/video`

**Can't get VNC feature to work: Disconnected**

Please check that you have `enableVNC = true` capability in your tests


**Seeing black screen with a cross in VNC window**

You are using `driver.close()` instead of `driver.quit()` and just closed the last browser tab instead of removing the session.

**Can Selenwright pull browser images automatically?**

No, we did not implement this feature intentionally. We consider that all such cluster maintenance tasks can influence performance and stability when done automatically.

**Is it possible to run Selenwright in Docker macvlan network?**

Yes, this is possible. See the following https://github.com/aqa-alex/selenwright/issues/795[Github issue] for possible solutions.
