== Saving Session Logs

[NOTE]
====
An additional `enableLog` capability should be added to tests. See <<Special Capabilities>> section for more details.
====

Selenwright can save log files for every running session to a separate file. By default log files are saved as `<session-id>.log` but you can alter file name via `logName` capability.

To enable this feature you only need to add `-log-output-dir </path/to/some/dir>` flag to Selenwright:

    $ ./selenwright -log-output-dir /path/to/some/dir

When running Selenwright **in Docker container** - don't forget to mount logs directory from the host machine:

.Example Docker Command
----
$ docker run -d                                 \
--name selenwright                                 \
-p 4444:4444                                    \
-v /var/run/docker.sock:/var/run/docker.sock    \
-v /data/logs/:/opt/selenwright/logs/              \
aqa-alex/selenwright:latest-release -log-output-dir /opt/selenwright/logs
----


=== Downloading Log Files from Selenwright

You can access saved log files using the following URL:

.Direct Link to Log File
----
http://selenwright-host.example.com:4444/logs/<filename>.log
----

NOTE: Direct link will work only after session has finished because Selenwright renames temporary filename to `<session-id>.log` (by default) at the session close.

To see all available files use:

.Listing All Log Files
----
http://selenwright-host.example.com:4444/logs/
----

=== Deleting Log Files

When <<Artifact History>> is enabled, log files are automatically cleaned up by the retention janitor. Otherwise, either remove log files from the directory using a scheduled job or send log removal requests:

.Deleting Log File via HTTP API
----
$ curl -X DELETE http://selenwright-host.example.com:4444/logs/<filename>.log
----
