== Quick Start Guide

=== Start Selenwright

. Make sure you have recent https://www.docker.com/[Docker] version installed.
. Download https://github.com/aerokube/cm/releases/latest[Configuration Manager] (Selenwright quick installation binary) for your platform from https://github.com/aerokube/cm/releases/latest[releases] page.
. On Linux or Mac give execution permissions to binary:

    $ chmod +x cm

. Run one command to start Selenwright:

    $ ./cm selenwright start --vnc
+
[WARNING]
====
Running this command with `sudo` can lead to broken installation. Recommended way is running Selenwright as regular user. On Linux to have permissions to access Docker you may need to add your user to `docker` group:
[source,bash]
----
$ sudo usermod -aG docker $USER
----
====
+

. Optionally run one more command to start Selenwright UI:

    $ ./cm selenwright-ui start

=== Run Your Tests

. Run your tests against Selenwright like you do with regular Selenium hub:
+
.Tests Endpoint
----
http://localhost:4444/wd/hub
----
+
If something does not work, you can easily check that Selenwright is running with opening *status* url:
+
.Current Selenwright Status
----
http://localhost:4444/status
----
+
A successful request should return a JSON with browser usage statistics.

. To open Selenwright UI navigate to the following page in your browser:
+
.UI Default URL
----
http://localhost:8080/
----

