== Updating Browsers

One of the most frequent Selenwright maintenance tasks is updating browser versions. To modify the list of available browsers you need to:

. Update browsers configuration file (aka `browsers.json`) by adding or deleting desired browser versions
. When adding new browsers in containers - pull respective container images, e.g.:

    $ docker pull selenwright/chrome:62.0

. Restart Selenwright or hot reload its configuration. 


=== The Short Way

This approach is mainly convenient for **personal usage** because Selenwright is restarted i.e. any running browser sessions are interrupted. Just type one https://github.com/aerokube/cm/releases/latest[Configuration Manager] command:

    $ ./cm selenwright update 

This command will download latest Selenwright release, browser images, generate new `browsers.json` and restart Selenwright. You may want to add `--vnc` flag to download images with VNC support:

    $ ./cm selenwright update --vnc

Another useful flag is total number of last browser versions to download (default is `2`):

    $ ./cm selenwright update --last-versions 5

If you wish to pull new images and regenerate configuration without restarting Selenwright then type:

    $ ./cm selenwright configure --vnc --last-versions 5

=== A Bit Longer Way

We recommend to use this approach on **production clusters** because Selenwright configuration is reloaded without restart.

. Edit `browsers.json` file and pull new browsers containers manually or using <<Syncing Browser Images from Existing File>>. Alternatively configure Selenwright without restarting it like shown in previous section.  
. Reload Selenwright configuration (see <<Reloading Configuration>> for more details):

    $ docker kill -s HUP selenwright

. To verify that configuration was reloaded you can check Selenwright health:

    $ curl -s http://example.com:4444/ping
    {"uptime":"<some-value>","lastReloadTime":"2017-05-12 12:33:06.322038542 +0300 MSK","numRequests":<some-number>}

+
Here `lastReloadTime` field shows when browsers configuration was reloaded for the last time.
